"""comment table update

Revision ID: 7268da1293e7
Revises: 642ca3b5ff49
Create Date: 2021-08-13 15:59:26.009284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7268da1293e7'
down_revision = '642ca3b5ff49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('post_id', sa.Integer(), nullable=False))
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.create_foreign_key(None, 'comment', 'post', ['post_id'], ['id'], ondelete='CASCADE')
    op.drop_column('comment', 'post')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('post', sa.INTEGER(), nullable=False))
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.create_foreign_key(None, 'comment', 'post', ['post'], ['id'], ondelete='CASCADE')
    op.drop_column('comment', 'post_id')
    # ### end Alembic commands ###
